etd:
  username: ~
  password: ~

timeouts:
  capybara: 60
  workflow: 200
  bulk_action: 200

sunet:
  id: ~ # NOTE: *without* @stanford.edu!
  password: ~

# for ETD test
dor_services_app:
  # NOTE:  this will need to be changed for qa
  url: 'https://dor-services-stage.stanford.edu'
  token: 'generate-yer-token-on-dor-services-app'

# for ETD test
workflow:
  # NOTE: for now, there is no access to the stage or qa workflow-service directly
  #  we must ssh tunnel instead ... maybe from etd-stage??
  url: 'https://workflow-service-stage.stanford.edu'
  logfile: 'tmp/workflow_service.log'

browser:
  driver: firefox
  height: 900
  width: 1440

default_apo: 'druid:qc410yz8746'
default_collection: 'druid:bc778pm9866'
